### Uploadind data from local machine to MongoDb

Loading csv dataset

In [3]:
import pandas as pd
import pymongo

df = pd.read_csv(r"C:\Users\Harshith N\Documents\Personal_projects\Customer-segmentation-MLOps-Pipeline\data\ecommerce_sales_analytics.csv")
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

df should be converted into dict before we push it to mongodb

In [4]:
data = df.to_dict(orient='records')

In [6]:
DB_NAME = "Customer-segmentation"
COLLECTION_NAME = "Customer-segmentation-data"
CONNECTION_URL = "mongodb+srv://harshith-admin:admin1234@customer-segmentation.mw4ci7w.mongodb.net/?appName=Customer-segmentation"

In [7]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

In [8]:
rec = collection.insert_many(data)

In [9]:
df = pd.DataFrame(list(collection.find()))
df.head(2)

,_id,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,69f4434b7db68afaf35cb1bc,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.2
1,69f4434b7db68afaf35cb1bd,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.1